### ISSUE TITLE
[Feature] Loading monsters from bestiary

### ISSUE THREAD

**Issue by marquesarthur** [Eddykasp/dnd-combat-sim#1]
Hi,

I'm sorry to bother you submitting an issue, but I think it may be of interest.
I'm writing a[ small DSL](https://github.com/marquesarthur/dnd-5e-tpk) to setup DnD encounters, and I'll probably convert the DSL into javascript code using your library. As my DSL will get more complex, I'll add things like levels, classes and so forth. 

As new requirements emerge, I may submit some pull requests in the near future. The first one will probably concern quickly creating monsters. [DnD.py](https://github.com/matteoferla/DnD-battler/blob/master/DnD.py) has a `bestiary.csv` file that I believe can be adapt to quickly instantiate monsters according to the csv data. Anyway, I only have ~3-4h/week to dedicate to that but I hope it interests you.

Cheers

edit: typos

**Comment by Eddykasp** [comment]
Yes automatic creation of monsters is a good suggestion and the csv does at a glance seem very compatible with my current API so I will take a look into what the best way to implement this would be.

As for future pull requests and suggestions, they are always welcome!

**Comment by Eddykasp** [comment]
Added parser in version 0.3.13
